"""job_site_credentials

Revision ID: 113adc516a45
Revises: b1c6c09b88b7
Create Date: 2024-11-01 10:37:36.468540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113adc516a45'
down_revision: Union[str, None] = 'b1c6c09b88b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_site_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('platform_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_job_site_credentials_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_site_credentials'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_site_credentials')
    # ### end Alembic commands ###
