"""add external_id to departments

Revision ID: 3cc6039d9dd5
Revises: 9993ef6d0ca3
Create Date: 2025-05-10 02:25:58.250834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc6039d9dd5'
down_revision: Union[str, None] = '9993ef6d0ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('department', sa.Column('external_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'external_type')
    op.drop_column('department', 'external_id')
    # ### end Alembic commands ###
