"""add org tables

Revision ID: 784176c9881e
Revises: 
Create Date: 2024-10-06 21:50:35.981415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784176c9881e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('corp_email', sa.String(), nullable=True),
    sa.Column('corp_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('full_name', name=op.f('uq_organization_full_name')),
    sa.UniqueConstraint('short_name', name=op.f('uq_organization_short_name'))
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_department_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    op.drop_table('organization')
    # ### end Alembic commands ###
