"""Add ogranization services policy

Revision ID: 9993ef6d0ca3
Revises: fdcecca38ca6
Create Date: 2025-03-28 13:19:01.315168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9993ef6d0ca3'
down_revision: Union[str, None] = 'fdcecca38ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_site_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('billing_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('platform_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_job_site_policy_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_site_policy'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_site_policy')
    # ### end Alembic commands ###
