"""add rights tables

Revision ID: b1c6c09b88b7
Revises: fcba7df14f07
Create Date: 2024-10-06 21:52:05.250831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c6c09b88b7'
down_revision: Union[str, None] = 'fcba7df14f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('right_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_rights'))
    )
    op.create_table('user_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['right_id'], ['spec_rights.id'], name=op.f('fk_user_rights_right_id_spec_rights')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_rights'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rights')
    op.drop_table('spec_rights')
    # ### end Alembic commands ###
