"""department_id_is_nullable

Revision ID: c793bc20fa9d
Revises: 4d8e79b23c15
Create Date: 2024-11-04 23:42:41.101639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c793bc20fa9d'
down_revision: Union[str, None] = '4d8e79b23c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
