"""add is_internal to user

Revision ID: cde2bf723f39
Revises: 9993ef6d0ca3
Create Date: 2025-04-29 12:16:51.643804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde2bf723f39'
down_revision: Union[str, None] = '3cc6039d9dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_internal', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_internal')
    # ### end Alembic commands ###
