"""add constraints field to u rights

Revision ID: f2e5d2ce23e0
Revises: 8242fa65870f
Create Date: 2025-02-25 15:27:34.593858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2e5d2ce23e0'
down_revision: Union[str, None] = '8242fa65870f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_rights', sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rights', 'constraints')
    # ### end Alembic commands ###
