"""add_user_agreement_table

Revision ID: fdcecca38ca6
Revises: f2e5d2ce23e0
Create Date: 2025-03-27 17:44:45.819728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcecca38ca6'
down_revision: Union[str, None] = 'f2e5d2ce23e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('agreement_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_user_agreement_organization_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_agreement_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_agreement'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agreement')
    # ### end Alembic commands ###
